name: photo_uploader
description: Flutter Photo Uploader is a Flutter package which uses the Camera package to take a picture, crop it, and post the data to an endpoint.
version: 0.3.0
homepage: https://nubeer.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  camera: ^0.5.8+5
  http: ^0.12.1
  path_provider: ^1.6.24
  path: ^1.6.4
  http_parser: ^3.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
